Merge scripts

diff --git a/setup-env b/setup-env
--- a/setup-env
+++ b/setup-env
@@ -1,28 +1,28 @@
 #!/bin/bash
 
-# Change the install location if necessary:
-prefix=/usr/local
-
 #{{{ Initialization
 
-	set +o histexpand -o errexit -o nounset
+	set +o histexpand -o errexit -o nounset -o pipefail
 	shopt -s extglob
 
+	dist="$(lsb_release -c | cut -f 2)"
+	setup="$(dirname "$0")/debian"
 	setup="$(dirname "$0")/mac"
 	common="$(dirname "$0")/common"
-	cfg="$HOME/.config/dotfiles"
 
-	source "$setup/functions.sh"
+	source "$common/functions.sh"
+	source "$common/config.sh"
 	source "$1"
-
-	export TMPDIR="${TMPDIR:-/private/tmp}"
-	export RBENV_ROOT="$prefix/rbenv"
-	export PYENV_ROOT="$prefix/pyenv"
-	export NVM_DIR="$prefix/nvm"
-	export PERLBREW_ROOT="$prefix/perlbrew"
 
 	echo "PATH = $PATH"
 	[[ ${PATH#*$prefix/bin} = "$PATH" ]] && export PATH="$prefix/bin:$PATH"
+	makedir "$prefix/bin"
+
+#}}}
+
+#{{{ Check for root access
+
+# [ -w ... ]
 
 #}}}
 
@@ -135,6 +135,69 @@ prefix=/usr/local
 	#}}}
 #}}}
 
+#{{{ Apt
+
+	#{{{ Repositories
+
+	echo ">> APT repositories"
+
+	exist apt-get || diecmd apt
+
+	if ! inlists download.virtualbox.org; then
+		echo "deb http://download.virtualbox.org/virtualbox/debian $dist contrib" \
+			>> /etc/apt/sources.list.d/oracle.list
+		download https://www.virtualbox.org/download/oracle_vbox_2016.asc | apt-key add - || warn "Can't add public key oracle_vbox_2016.asc"
+		download https://www.virtualbox.org/download/oracle_vbox.asc | apt-key add - || warn "Can't add public key oracle_vbox.asc"
+	fi
+
+	inlists rabbitvcs || add-apt-repository ppa:rabbitvcs/ppa
+	inlists universe || add-apt-repository universe
+	inlists zeal-developers || add-apt-repository ppa:zeal-developers/ppa
+
+	#}}}
+
+	#{{{ Packages
+
+	echo ">> APT packages"
+
+	exist 7z           || install p7zip
+	exist ag           || install silversearcher-ag
+	exist autoconf     || install autoconf
+	exist automake     || install automake
+	exist clipit       || install clipit
+	exist dconf-editor || install dconf-editor
+	exist dkms         || install dkms
+	exist dropbox      || install dropbox
+	exist gimp         || install gimp
+	exist git          || install git
+	exist gnome-tweak-tool || install gnome-tweak-tool
+	exist gpick        || install gpick
+	exist gvim         || install vim-gtk
+	exist java         || install default-jre
+	# exist latex      || install texlive texlive-lang-german texlive-latex-extra
+	# exist latexmk    || install latexmk
+	exist libtoolize   || install libtool
+	exist mount.exfat  || install exfat-fuse exfat-utils
+	exist nitrogen     || install nitrogen
+	exist rename       || install rename
+	exist rabbitvcs    || install rabbitvcs-nautilus rabbitvcs-cli
+	exist shellcheck   || install shellcheck
+	exist svn          || install subversion
+	exist tree         || install tree
+	exist virtualbox   || install virtualbox-5.1
+	exist zeal         || install zeal
+	exist zsh          || install zsh
+
+	if ! exist google-chrome; then
+		download https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb "$TMPDIR/google-chrome.deb"
+		rundel dpkg -i "$TMPDIR/google-chrome.deb"
+	fi
+
+	install -f
+
+	#}}}
+#}}}
+
 #{{{ Shared files
 
 	echo ">> Shared files"
@@ -215,6 +278,7 @@ prefix=/usr/local
 	if ! islocal python; then
 		ver="$(pyenv install --list | sort -nr | perl -ne 'next unless /^\s*\d+\.\d+(\.\d+)?\n$/; s/\s//g; print; exit;')"
 		[ "$ver" ] || die "Can't fetch latest Python version"
+		pyenv install "$ver" || die "Can't install Python"
 		CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install "$ver" || die "Can't install Python"
 		pyenv global "$ver"
 	fi
@@ -236,6 +300,22 @@ prefix=/usr/local
 
 	echo ">> Vim"
 
+	[ -f "$setup/vim" ] || die "Can't find vim script"
+
+	islocal vim      || copy "$setup/vim" $prefix/bin
+	islocal vi       || link $prefix/bin/vim $prefix/bin/vi
+	islocal gvim     || link $prefix/bin/vim $prefix/bin/gvim
+	islocal rvim     || link $prefix/bin/vim $prefix/bin/rvim
+	islocal rgvim    || link $prefix/bin/vim $prefix/bin/rgvim
+	islocal view     || link $prefix/bin/vim $prefix/bin/view
+	islocal gview    || link $prefix/bin/vim $prefix/bin/gview
+	islocal vimdiff  || link $prefix/bin/vim $prefix/bin/vimdiff
+	islocal gvimdiff || link $prefix/bin/vim $prefix/bin/gvimdiff
+	islocal viman    || link $prefix/bin/vim $prefix/bin/viman
+	islocal gviman   || link $prefix/bin/vim $prefix/bin/gviman
+
+	echo ">> MacVim"
+
 	[ -r "$setup/mvim" ] || die "Can't find mvim script"
 	diff "$setup/mvim" $prefix/bin/mvim &> /dev/null || copy "$setup/mvim" $prefix/bin
 
@@ -254,8 +334,7 @@ prefix=/usr/local
 	islocal viman    || link $prefix/bin/mvim $prefix/bin/viman
 	islocal mviman   || link $prefix/bin/mvim $prefix/bin/mviman
 	islocal gviman   || link $prefix/bin/mvim $prefix/bin/gviman
-
-	islocal vim || diecmd mvim
+	islocal vim || diecmd vim
 
 	download http://ftp.vim.org/pub/vim/runtime/spell/de.utf-8.spl "$HOME/.vim/spell/de.utf-8.spl"
 	download https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim "$HOME/.vim/autoload/plug.vim"
@@ -285,7 +364,22 @@ prefix=/usr/local
 
 	echo ">> Base16"
 
-	_base16() {
+	_base16_linux() {
+		for s in color-scripts/*-256.sh; do
+			echo "${s/color-scripts\//}"
+			sed -i -e "s/\"base 16 /\"/i" -e "s/ 256\"/\"/" "$s"
+			bash "$s"
+		done
+	}
+
+	if ! dconf dump /org/gnome/terminal/legacy/profiles:/ | grep -qi harmonic16; then
+		clone https://github.com/aaron-williamson/base16-gnome-terminal.git "$TMPDIR/base16-terminal"
+		rundel "$TMPDIR/base16-terminal" _base16_linux
+	fi
+
+	echo ">> Base16 Mac"
+
+	_base16_mac() {
 		for p in profiles/*.terminal; do
 			xattr -d com.apple.quarantine "$p"
 			open "$p"
@@ -294,7 +388,7 @@ prefix=/usr/local
 
 	if ! plutil -p "$HOME/Library/Preferences/com.apple.Terminal.plist" | grep -qi harmonic16; then
 		clone https://github.com/vbwx/base16-terminal-app.git "$TMPDIR/base16-terminal"
-		rundel "$TMPDIR/base16-terminal" _base16
+		rundel "$TMPDIR/base16-terminal" _base16_mac
 	fi
 
 #}}}
@@ -303,16 +397,73 @@ prefix=/usr/local
 
 	echo ">> Powerline fonts"
 
-	if ! inhome Library/Fonts/Hack-Regular.ttf; then
+	font_path=.local/share/fonts
+	font_path=Library/Fonts
+	if ! inhome "$font_path/Hack-Regular.ttf"; then
 		clone https://github.com/powerline/fonts.git "$TMPDIR/powerline-fonts"
 		rundel "$TMPDIR/powerline-fonts" bash install.sh
 	fi
 
 #}}}
 
-#{{{ Set PATH for all apps
+#{{{ Distribution-specific setup
 
-	echo ">> Set PATH for all apps"
+	#{{{ Keyboard configuration
+
+	echo ">> Keyboard configuration"
+
+	# Map [Shift]+[Backspace] to [Delete]
+	for file in pc inet us macintosh_vndr/apple macintosh_vndr/us; do
+		modify "s/backspace,[[:space:]]*backspace/BackSpace, Delete/ig" /usr/share/X11/xkb/symbols/$file
+	done
+
+	gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us+mac'), ('xkb', 'de')]"
+	gsettings set org.gnome.desktop.input-sources xkb-options "['lv3:ralt_switch', 'ctrl:swap_lwin_lctl', 'ctrl:swap_rwin_rctl', 'terminate:ctrl_alt_bksp']"
+
+	#}}}
+
+	#{{{ Startup applications
+
+	echo ">> Startup applications"
+
+	if ! inhome .config/autostart/mouse-speed.desktop; then
+		[ -d "$HOME/.local/bin" ] || mkdir -p "$HOME/.local/bin"
+		xinput --list --short
+		echo -n "IDs of your pointing devices (space-separated): "
+		read ids
+		file="$setup/mouse-speed"
+		modify "s/\$ids/$ids/" "$file"
+		copy "$file" "$HOME/.local/bin"
+		file="$setup/mouse-speed.desktop"
+		modify "s/~\\//$HOME\\//" "$file"
+		copy "$file" "$HOME/.config/autostart"
+	fi
+	if ! inhome .config/autostart/nitrogen.desktop; then
+		copy "$setup/nitrogen.desktop" "$HOME/.config/autostart"
+		nitrogen &> /dev/null & || diecmd nitrogen
+	fi
+
+	#}}}
+
+	#{{{ Modify application shortcuts
+
+	echo ">> Modify application shortcuts"
+
+	file="/usr/share/applications/google-chrome.desktop"
+	modify "s/google-chrome[[:alnum:]\\-]*/& --enable-native-gpu-memory-buffers/g" $file
+
+	#}}}
+
+	#{{{ Login settings
+
+	inshare lightdm && copy "$setup/02_user.conf" "/usr/share/lightdm/lightdm.conf.d"
+
+	#}}}
+#}}}
+
+#{{{ PATH for all apps
+
+	echo ">> PATH for all apps"
 
 	lpaths=(
 		$prefix/bin
@@ -341,9 +492,18 @@ prefix=/usr/local
 		cat "$TMPDIR/paths"
 		sudo mv -v -f "$TMPDIR/paths" /etc || exit 1
 	fi
-	if ! grep -sq "texbin" /etc/paths /etc/paths.d/*; then
+	if ! grep -sq texbin /etc/paths /etc/paths.d/*; then
 		echo "$(IFS=$'\n'; printf "${texpaths[*]}")\n" | sudo tee /etc/paths.d/TeX > /dev/null
 	fi
+
+
+#}}}
+
+#{{{ Cleanup
+
+	echo ">> Cleanup"
+
+	rm -rf "$prefix/Caskroom/mactex"
 
 #}}}
 
