Last commit

diff --git a/common/tpl/rebuild b/common/tpl/rebuild
--- a/common/tpl/rebuild
+++ b/common/tpl/rebuild
@@ -7,22 +7,21 @@ targets=(
 )
 
 function help {
-	echo "The rebuild utility provides a simple interface to rebuild caches and databases."
+	printf "The rebuild utility provides a simple interface to rebuild caches and databases.\n"
 	usage
 }
 
 function usage {
-	echo -en "\nusage: rebuild (all"
+	printf "\nusage: rebuild (all"
 	for t in ${targets[*]}; do
-		echo -n " | $t"
+		printf " | $t"
 	done
-	echo ")"
-	echo "       rebuild help"
+	printf ")\n       rebuild help\n"
 	exit $*
 }
 
-if [ $# -eq 0 ]; then
-	>&2 echo "rebuild: target missing"
+if [[ $# -eq 0 ]]; then
+	>&2 printf "rebuild: target missing\n"
 	usage 1
 fi
 
@@ -39,10 +38,10 @@ for t in $*; do
 			;;
 		(*)
 			alt=($(which -a rebuild))
-			if [ ${#alt[@]} -gt 1 ]; then
+			if [[ ${#alt[@]} -gt 1 ]]; then
 				${alt[1]} "$@"
 			else
-				>&2 echo "rebuild: unknown target: $t"
+				>&2 printf "rebuild: unknown target: $t\n"
 				usage 1
 			fi
 	esac
diff --git a/common/tpl/update b/common/tpl/update
--- a/common/tpl/update
+++ b/common/tpl/update
@@ -19,22 +19,21 @@ targets=(
 )
 
 function help {
-	echo "The update utility provides a simple interface to perform updates of programs and packages."
+	printf "The update utility provides a simple interface to perform updates of programs and packages.\n"
 	usage
 }
 
 function usage {
-	echo -en "\nusage: update (all"
+	printf "\nusage: update (all"
 	for t in ${targets[*]}; do
-		echo -n " | $t"
+		printf " | $t"
 	done
-	echo ")"
-	echo "       update help"
+	printf ")\n       update help\n"
 	exit $*
 }
 
-if [ $# -eq 0 ]; then
-	>&2 echo "update: target missing"
+if [[ $# -eq 0 ]]; then
+	>&2 printf "update: target missing\n"
 	usage 1
 fi
 
@@ -87,7 +86,7 @@ for t in $*; do
 			gem cleanup
 			;;
 		(vim)
-			[ -f "$HOME/.vim/autoload/plug.vim" ] && vim +PlugUpgrade +PlugUpdate +qall
+			[[ -f "$HOME/.vim/autoload/plug.vim" ]] && vim +PlugUpgrade +PlugUpdate +qall
 			;;
 		(texlive)
 			sudo tlmgr update --all
@@ -97,10 +96,10 @@ for t in $*; do
 			;;
 		(*)
 			alt=($(which -a update))
-			if [ ${#alt[@]} -gt 1 ]; then
+			if [[ ${#alt[@]} -gt 1 ]]; then
 				${alt[1]} "$@"
 			else
-				>&2 echo "update: unknown target: $t"
+				>&2 printf "update: unknown target: $t\n"
 				usage 1
 			fi
 	esac
